# Generated by Django 4.0.4 on 2023-01-13 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_input_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='index',
        ),
        migrations.RemoveField(
            model_name='test',
            name='index',
        ),
        migrations.AddField(
            model_name='test',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 16, 39, 7, 60384)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='homework',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 17, 9, 30, 949221)),
            preserve_default=False,
        ),
    ]
