# Generated by Django 4.0.4 on 2023-01-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_lecture_index_remove_test_index_test_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='lesson',
        ),
    ]
