# Generated by Django 4.0.4 on 2023-01-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_test_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='exercise',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
