# Generated by Django 4.0.4 on 2023-01-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_remove_lesson_lesson_type_linkage'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkage',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.lesson'),
            preserve_default=False,
        ),
    ]
